"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nest_menubar.py']
APP_NAME = 'NestMenubar'
DATA_FILES = ['nest_menubar.icns']
OPTIONS = {
    'iconfile': 'nest_menubar.icns',
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Control Nest thermostats",
        'CFBundleIdentifier': "ai.moll.nestmenubar",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2019, Mark Moll, All Rights Reserved",
        'LSUIElement': True
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['python-nest>=4.1.0', 'rumps>=0.3.0']
)
